import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "@pal/utils/Provider";
import { ThemeProvider } from "@pal/components/ui/ThemeProvider";
import { Sidebar } from "@pal/components/Sidebar/Sidebar";
import "./globals.css";
import { Toaster } from "@pal/components/ui/sonner";

const inter = Inter({
  variable: "--font-inter", // Set up a custom variable for Inter font
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Add desired font weights
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body className={`${inter.variable} antialiased h-full`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Provider>
            <Sidebar />
            <div className="md:ml-[174px] pb-[72px] md:pb-0">
              {children}
              <Toaster />
            </div>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
